# Recipe to build Tensorflow meta package
{% set build_version = "2.13.0" %}

package:
  name: tensorflow{{ '' if build_type == 'cuda' else '-cpu' }}
  version: {{ build_version }}

build:
  number: 1
  string: py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}   #[build_type == 'cpu']
  string: {{ build_type }}{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }} #[build_type == 'cuda']

requirements:
  run:
    - tensorflow-base        {{ build_version }}
    - _tensorflow_select     {{ tensorflow_select_version }}
    - tensorboard          =={{ tensorboard }}
    - tensorflow-estimator =={{ tf_estimator }}
    - keras                =={{ keras }}
    - tensorflow-io-gcs-filesystem {{ tensorflow_io_gcs_filesystem }} [not s390x]
    - python                 {{ python }}
    - cudatoolkit            {{ cudatoolkit }} #[build_type == 'cuda']

test:
  imports:
    - tensorflow

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: Meta-package to install {{ 'GPU-enabled' if build_type == 'cuda' else 'CPU-only' }} TensorFlow variant
  description: Meta-package to install {{ 'GPU-enabled' if build_type == 'cuda' else 'CPU-only' }} TensorFlow variant
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org
  doc_source_url: https://github.com/tensorflow/docs

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team

