# Recipe to build Tensorflow meta package
{% set build_version = "2.4.0" %}
{% set estimator_version = "2.4.0" %}

package:
  name: tensorflow{{ '' if build_type == 'cuda' else '-cpu' }}
  version: {{ build_version }}

build:
  number: 2
  string: py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}   #[build_type == 'cpu']
  string: {{ build_type }}{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }} #[build_type == 'cuda']

requirements:
  run:
    - tensorflow-base        {{ build_version }}
    - _tensorflow_select     {{ tensorflow_select_version }}
    - tensorboard          =={{ tensorboard }}
    - tensorflow-estimator =={{ estimator_version }}
    - python                 {{ python }}
    - cudatoolkit            {{ cudatoolkit }} #[build_type == 'cuda']

about:
  summary: Meta-package to install {{ 'GPU-enabled' if build_type == 'cuda' else 'CPU-only' }} TensorFlow variant

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team

