recipes:
  - name : tensorflow-select
    path : select_recipe

  - name : tensorflow-base
    path : recipe
    resources:
       memory: 200Gi  #[ppc64le]
       memory: 10Gi   #[not ppc64le]

  - name : tensorflow-meta
    path : meta_recipe

