# Recipe to build Tensorflow select packages

package:
  name: _tensorflow_select
  version: {{ tensorflow_select_version }}

build:
  number: 2
  string: {{ build_type }}_{{ PKG_BUILDNUM }}

about:
  summary : Package used to select the specific Tensorflow build variant

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
