name: Open-CE Feedstock PR Tests

on:
  pull_request:
    branches: [main]

jobs:
  python-setup-worflow:
    uses: open-ce/open-ce/.github/workflows/python-setup@nish-github
    with:
      username: Open-CE
    secrets: inherit
  optional_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
      - uses: open-ce/open-ce/.github/actions/feedstock-optional-pr@nish-github
  required_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
      - uses: open-ce/open-ce/.github/actions/feedstock-required-pr@nish-github
